### ISSUE TITLE
[BUG] app init panics with the "single-threaded" feature

### ISSUE THREAD

**Issue by j-kawa** [fltk-rs/fltk-rs#1526]
## Describe the bug
since the commit ac16f146dd19b083af3c486abd9f954450dc7d7f the `fltk::app::init_all` function panics when the user opts in for the `single-threaded` feature

## To Reproduce
```
$ RUST_BACKTRACE=1 cargo run --example hello_button --features single-threaded
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/examples/hello_button`
thread 'main' panicked at fltk/src/app/init.rs:60:13:
fltk-rs requires threading support!
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: fltk::app::init::init_all
             at ./fltk/src/app/init.rs:60:13
   3: <fltk::app::App as core::default::Default>::default
             at ./fltk/src/app/mod.rs:39:9
   4: hello_button::main
             at ./fltk/examples/hello_button.rs:4:15
   5: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Expected behavior
the `fltk::app::init_all` doesn't panic 

## Desktop info
 - OS: Linux
 - Version `master`
 - Display server: x11

**Comment by MoAlyousef** [comment]
Thank you for the report.
I've pushed a fix.
Can you try with latest master?

**Comment by j-kawa** [comment]
that worked, thank you
