### ISSUE TITLE
[BUG] Something goes wrong with TextDisplay.set_highlight_data

### ISSUE THREAD

**Issue by jcbritobr** [fltk-rs/fltk-rs#752]
Function TextDisplay.set_highlight_data got panic when  filling with Option<TextBuffer> and Vec<StyleTableEntry>
```rust
use fltk::{
    app::{App, Scheme},
    enums::{Color, Font},
    prelude::{DisplayExt, GroupExt, WidgetBase, WidgetExt},
    text::{StyleTableEntry, TextBuffer, TextDisplay},
    window::Window,
};

const WIDGET_PADDING: i32 = 20;
const WIDGET_WIDTH: i32 = 640;
const WIDGET_HEIGHT: i32 = 480;

fn main() {
    let app = App::default().with_scheme(Scheme::Gtk);
    let mut win = Window::default().with_size(WIDGET_WIDTH, WIDGET_HEIGHT);

    let mut style_entry_buffer = Vec::<StyleTableEntry>::new();
    style_entry_buffer.push(StyleTableEntry {
        color: Color::Red,
        font: Font::Courier,
        size: 16,
    });
    style_entry_buffer.push(StyleTableEntry {
        color: Color::DarkYellow,
        font: Font::Courier,
        size: 16,
    });
    style_entry_buffer.push(StyleTableEntry {
        color: Color::DarkGreen,
        font: Font::Courier,
        size: 16,
    });
    style_entry_buffer.push(StyleTableEntry {
        color: Color::Blue,
        font: Font::Courier,
        size: 16,
    });

    let mut text_buffer = TextBuffer::default();
    let mut style_buffer = TextBuffer::default();

    text_buffer.set_text(
        "Red Line 1\nYel Line 2\nGrn Line 3\nBlu Line 4\n\
            Red Line 5\n Yel Line 6\nGrn Line 7\nBlu Line 8",
    );

    style_buffer.set_text("AAAAAAAAAA\nBBBBBBBBBB\nCCCCCCCCCC\nDDDDDDDDDD\nAAAAAAAAAA\nBBBBBBBBBB\nCCCCCCCCCC\nDDDDDDDDDD\n");

    let mut disp = TextDisplay::new(
        WIDGET_PADDING,
        WIDGET_PADDING,
        WIDGET_WIDTH - 40,
        WIDGET_HEIGHT - 40,
        "Display",
    );
    disp.set_highlight_data(Some(style_buffer), style_entry_buffer);

    disp.set_buffer(text_buffer);
    win.resizable(&disp);
    win.show();

    app.run().unwrap();
}
```

Expected behavior is to color the TextDisplay below image:

![image](https://user-images.githubusercontent.com/6579862/123835788-588eeb00-d8df-11eb-946c-94a4619c2cba.png)

Below, my stack trace:
```
$ cargo run --bin fl_text_display_colors
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target\debug\fl_text_display_colors.exe`
thread 'main' panicked at 'assertion failed: self.buffer().is_some()', C:\Users\jcbritobr\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-1.0.20\src\text.rs:552:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\std\src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\core\src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b\/library\core\src/panicking.rs:50:5
   3: <fltk::text::TextDisplay as fltk::prelude::DisplayExt>::set_highlight_data
             at .\C:\Users\jcbritobr\.cargo\registry\src\github.com-1ecc6299db9ec823\fltk-1.0.20\src/text.rs:552:33
   4: fl_text_display_colors::main
             at .\src/fl_text_display_colors.rs:59:5
   5: core::ops::function::FnOnce::call_once
             at .\C:\Users\jcbritobr\.rustup\toolchains\stable-x86_64-pc-windows-gnu\lib/rustlib/src/rust\library\core\src\ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\fl_text_display_colors.exe` (exit code: 101)
```

**Comment by MoAlyousef** [comment]
Hi
The code is hitting an assert because you're calling `disp.set_highlight_data` before `disp.set_buffer`. If you change the order it should work:
```rust
    disp.set_buffer(text_buffer);
    disp.set_highlight_data(Some(style_buffer), style_entry_buffer);
```
I think the assert can be relaxed. I'll test things out, and if it can, I'll remove it in the next version.

**Comment by jcbritobr** [comment]
> 
> 
> Hi
> The code is hitting an assert because you're calling `disp.set_highlight_data` before `disp.set_buffer`. If you change the order it should work:
> 
> ```rust
>     disp.set_buffer(text_buffer);
>     disp.set_highlight_data(Some(style_buffer), style_entry_buffer);
> ```
> 
> I think the assert can be relaxed. I'll test things out, and if it can, I'll remove it in the next version.

Hello,
I'll test it now. Im porting ercos cheat page for rust. If I get more issues, I'll post them here.

**Comment by jcbritobr** [comment]
Yep, it works. Maybe put a word about this in docs can be a good fix?
 
![image](https://user-images.githubusercontent.com/6579862/123838836-cd175900-d8e2-11eb-8f91-9a20d90c62c6.png)

**Comment by MoAlyousef** [comment]
I've removed the assert since it appears to be unnecessary
